xcopy /y .\Dependencies\OGRE\bin\release\OgreMain.dll .\bin\release\
xcopy /y .\Dependencies\OGRE\bin\release\Plugin_CgProgramManager.dll .\bin\release\
xcopy /y .\Dependencies\OGRE\bin\release\cg.dll .\bin\release\
xcopy /y .\Dependencies\OGRE\bin\release\OIS.dll .\bin\release\
xcopy /y .\Dependencies\OGRE\bin\release\RenderSystem_GL.dll .\bin\release\
xcopy /y .\Dependencies\MyGUI\bin\release\MyGUIEngine.dll .\bin\release\
xcopy /y .\Dependencies\OGRE\config\release\plugins.cfg .\bin\release\
xcopy /y .\Dependencies\OpenCV\bin\release\opencv_core247.dll .\bin\release\
xcopy /y .\Dependencies\OpenCV\bin\release\opencv_highgui247.dll .\bin\release\
xcopy /y .\Dependencies\OpenCV\bin\release\opencv_imgproc247.dll .\bin\release\
xcopy /y .\Dependencies\GeometryPlusPlus\bin\release\geometryplusplus.dll .\bin\release\
xcopy /y .\magic3d.cfg .\bin\release\

xcopy /y .\Dependencies\OGRE\bin\debug\OgreMain_d.dll .\bin\debug\
xcopy /y .\Dependencies\OGRE\bin\debug\Plugin_CgProgramManager_d.dll .\bin\debug\
xcopy /y .\Dependencies\OGRE\bin\debug\cg.dll .\bin\debug\
xcopy /y .\Dependencies\OGRE\bin\debug\OIS_d.dll .\bin\debug\
xcopy /y .\Dependencies\OGRE\bin\debug\RenderSystem_GL_d.dll .\bin\debug\
xcopy /y .\Dependencies\MyGUI\bin\debug\MyGUIEngine_d.dll .\bin\debug\
xcopy /y .\Dependencies\OGRE\config\debug\plugins.cfg .\bin\debug\
xcopy /y .\Dependencies\OpenCV\bin\debug\opencv_core247d.dll .\bin\debug\
xcopy /y .\Dependencies\OpenCV\bin\debug\opencv_highgui247d.dll .\bin\debug\
xcopy /y .\Dependencies\OpenCV\bin\debug\opencv_imgproc247d.dll .\bin\debug\
xcopy /y .\Dependencies\GeometryPlusPlus\bin\debug\geometryplusplus.dll .\bin\debug\
xcopy /y .\magic3d.cfg .\bin\debug\
